import { Noto_Sans_TC } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const notoSansTC = Noto_Sans_TC({ subsets: ['latin'] });

export const metadata = {
  title: 'Personality-Test',
  description: 'Generated by GoFlow',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="cn">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={notoSansTC.className}>
        <Navbar/>
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
